services:
  localstack:
    image: localstack/localstack:0.14.1
    container_name: localstack
    ports:
      - "4566:4566"
    volumes:
      - "./scripts/localstack-init:/docker-entrypoint-initaws.d"
      - "./scripts/data/test-bucket:/data"
    environment:
      - SERVICES=s3

  google-cloud:
    image: fsouza/fake-gcs-server
    container_name: google-cloud
    ports:
      - 8080:8080
    volumes:
      - ./scripts/data:/data
    command: [ "-scheme", "http", "-port", "8080", "-external-url", "http://localhost:8080", "-backend", "memory" ]

